version: '3.5'
services:
    web:
        build: ./web
        expose:
            - '8082'
        environment:
            ALIAS: '/'
            PORT: '8082'
            CLIENT_ID: $CLIENT_ID
            CLIENT_SECRET: $CLIENT_SECRET
        depends_on:
            - db
        networks:
          - proxy
          - backend
        restart: always
    db:
        build: ./db
        expose:
            - '3306'
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
        restart: always
        networks:
          - backend
volumes:
    db:

networks:
    proxy:
        name: nginx_reverse_proxy
    backend:
